### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xkfen**

### CODE REVIEW

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[rubinus](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999479965 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[rubinus](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999479965 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[rubinus](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999479965 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[rubinus](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999479965 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[23456346](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999480886 "Approved")*, *[rubinus](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999479965 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[23456346](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999480886 "Approved")*, *[rubinus](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999479965 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[23456346](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999480886 "Approved")*, *[rubinus](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999481670 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[23456346](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999480886 "Approved")*, *[rubinus](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999481670 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[23456346](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999480886 "Approved")*, *[rubinus](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999515364 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rubinus** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[23456346](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999480886 "Approved")*, *[rubinus](https://github.com/gitcpu-io/jx-azure/pull/12#issuecomment-999515364 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=gitcpu-io%2Fjx-azure).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitcpu-io/jx-azure/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rubinus — COMMENTED** [review]
看过

**Review by 23456346 — COMMENTED** [review]
也看过

**Review by 23456346 — APPROVED** [review]

**Review by rubinus — APPROVED** [review]

**Pull request closed without merging**
